/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package e2eTestWithRestAssuredInKotlin

import org.hamcrest.CoreMatchers.*
import org.junit.Assert.*
import kotlin.test.Test

class AppTest {
    @Test fun testAppHasAGreeting() {
    }
}
